### Análise do dataset
O dataset trabalhado foi originado do Kaggle, entitulado Years of Schooling Worldwide, disponibilizado pelo usuários 'iamsouravbanerjee' em formato .csv(-https://www.kaggle.com/datasets/iamsouravbanerjee/years-of-schooling-worldwide)

Realizei o download do dataset através da API do Kaggle, e fiz uma análise inicial com Python, visando verificar as informações disponibilizadas e realizar uma análise prévia.

In [3]:
# bibliotecas utlizadas 
import pandas as pd
import numpy as np

import kaggle                                           
from kaggle.api.kaggle_api_extended import KaggleApi

In [4]:
#realizando o download do arquivo.csv (resposta False pois já havia realizado o download anteriormente utilizando o mesmo processo)
api = KaggleApi()
api.authenticate()

api.dataset_download_file('iamsouravbanerjee/years-of-schooling-worldwide', 'schooling.csv')

False

In [5]:
df = pd.read_csv('schooling.csv')
df.head()

,ISO3,Country,Continent,Hemisphere,Human Development Groups,UNDP Developing Regions,HDI Rank (2021),Expected Years of Schooling (1990),Expected Years of Schooling (1991),Expected Years of Schooling (1992),...,Expected Years of Schooling (2012),Expected Years of Schooling (2013),Expected Years of Schooling (2014),Expected Years of Schooling (2015),Expected Years of Schooling (2016),Expected Years of Schooling (2017),Expected Years of Schooling (2018),Expected Years of Schooling (2019),Expected Years of Schooling (2020),Expected Years of Schooling (2021)
0,AFG,Afghanistan,Asia,Northern Hemisphere,Low,SA,180.0,2.50405,2.80655,3.10905,...,9.577323,9.875836,10.174350,10.180150,10.185950,10.191750,10.197550,10.263844,10.263844,10.263844
1,AGO,Angola,Africa,Southern Hemisphere,Medium,SSA,148.0,3.53748,3.32483,3.30209,...,10.082500,10.604900,11.127300,11.649700,12.172090,12.172100,12.172100,12.172100,12.172100,12.172100
2,ALB,Albania,Europe,Northern Hemisphere,High,ECA,67.0,11.60293,11.76358,10.66378,...,14.586650,14.925640,15.252420,15.076300,14.804600,14.816130,14.695620,14.818920,14.448000,14.448000
3,AND,Andorra,Europe,Northern Hemisphere,Very High,NaN,40.0,10.79878,10.79878,10.79878,...,13.524016,13.138841,13.495076,13.140280,13.300239,13.046476,13.300239,13.300239,13.300239,13.300239
4,ARE,United Arab Emirates,Asia,Northern Hemisphere,Very High,AS,26.0,10.47456,10.82239,10.65938,...,12.945893,13.064747,13.183602,13.302456,13.421310,14.344100,15.019120,15.694140,15.717690,15.717690

In [6]:
#Verificação do conteúdo do dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 195 entries, 0 to 194
Data columns (total 39 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   ISO3                                195 non-null    object
 1   Country                             195 non-null    object
 2   Continent                           195 non-null    object
 3   Hemisphere                          195 non-null    object
 4   Human Development Groups            191 non-null    object
 5   UNDP Developing Regions             151 non-null    object
 6   HDI Rank (2021)                     191 non-null    float64
 7   Expected Years of Schooling (1990)  171 non-null    float64
 8   Expected Years of Schooling (1991)  171 non-null    float64
 9   Expected Years of Schooling (1992)  171 non-null    float64
 10  Expected Years of Schooling (1993)  171 non-null    float64
 11  Expected Years of Schooling (1994)  171 non-null    float64
 12  Expected Years of Schooling (1995)  175 non-null    float64
 13  Expected Years of Schooling (1996)  175 non-null    float64
 14  Expected Years of Schooling (1997)  175 non-null    float64
 15  Expected Years of Schooling (1998)  175 non-null    float64
 16  Expected Years of Schooling (1999)  177 non-null    float64
 17  Expected Years of Schooling (2000)  186 non-null    float64
 18  Expected Years of Schooling (2001)  186 non-null    float64
 19  Expected Years of Schooling (2002)  188 non-null    float64
 20  Expected Years of Schooling (2003)  188 non-null    float64
 21  Expected Years of Schooling (2004)  188 non-null    float64
 22  Expected Years of Schooling (2005)  189 non-null    float64
 23  Expected Years of Schooling (2006)  189 non-null    float64
 24  Expected Years of Schooling (2007)  190 non-null    float64
 25  Expected Years of Schooling (2008)  190 non-null    float64
 26  Expected Years of Schooling (2009)  190 non-null    float64
 27  Expected Years of Schooling (2010)  191 non-null    float64
 28  Expected Years of Schooling (2011)  191 non-null    float64
 29  Expected Years of Schooling (2012)  191 non-null    float64
 30  Expected Years of Schooling (2013)  191 non-null    float64
 31  Expected Years of Schooling (2014)  191 non-null    float64
 32  Expected Years of Schooling (2015)  192 non-null    float64
 33  Expected Years of Schooling (2016)  192 non-null    float64
 34  Expected Years of Schooling (2017)  192 non-null    float64
 35  Expected Years of Schooling (2018)  193 non-null    float64
 36  Expected Years of Schooling (2019)  193 non-null    float64
 37  Expected Years of Schooling (2020)  193 non-null    float64
 38  Expected Years of Schooling (2021)  193 non-null    float64
dtypes: float64(33), object(6)
memory usage: 59.5+ KB

#### Análise de dados nulos
Podemos verificar que existem dados faltantes em diversas colunas:

- Human Development Groups;
- UNDP Developing Regions;
- HDI Rank (2021);
- Expected Years of Schooling(1990 - 2021)

Abaixo analisei cada caso separadamente.

#### Human Development Groups

In [7]:
df.loc[df['Human Development Groups'].isna() ]

,ISO3,Country,Continent,Hemisphere,Human Development Groups,UNDP Developing Regions,HDI Rank (2021),Expected Years of Schooling (1990),Expected Years of Schooling (1991),Expected Years of Schooling (1992),...,Expected Years of Schooling (2012),Expected Years of Schooling (2013),Expected Years of Schooling (2014),Expected Years of Schooling (2015),Expected Years of Schooling (2016),Expected Years of Schooling (2017),Expected Years of Schooling (2018),Expected Years of Schooling (2019),Expected Years of Schooling (2020),Expected Years of Schooling (2021)
108,MCO,Monaco,Europe,Northern Hemisphere,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
132,NRU,Nauru,Oceania,Southern Hemisphere,NaN,EAP,NaN,NaN,NaN,NaN,...,10.290049,10.479331,10.672094,10.868403,11.068323,11.271921,11.479264,11.69042,11.69042,11.69042
142,PRK,North Korea,Asia,Northern Hemisphere,NaN,EAP,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,10.746180,10.777645,10.783170,10.783170,10.78317,10.78317,10.78317
158,SOM,Somalia,Africa,Northern Hemisphere,NaN,AS,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
df['Human Development Groups'].unique()

array(['Low', 'Medium', 'High', 'Very High', nan], dtype=object)

Em pesquisa ao site do "Human Development Report", constatei que os 4 países que não apresentam dados de 'Human Development Groups' também não estão descritos no site (https://hdr.undp.org/data-center/country-insights#/ranks). Para evitar erros de classificação, deixarei o valor NaN.

### HDI Rank (2021)

In [9]:
df.loc[df['HDI Rank (2021)'].isna() ]

,ISO3,Country,Continent,Hemisphere,Human Development Groups,UNDP Developing Regions,HDI Rank (2021),Expected Years of Schooling (1990),Expected Years of Schooling (1991),Expected Years of Schooling (1992),...,Expected Years of Schooling (2012),Expected Years of Schooling (2013),Expected Years of Schooling (2014),Expected Years of Schooling (2015),Expected Years of Schooling (2016),Expected Years of Schooling (2017),Expected Years of Schooling (2018),Expected Years of Schooling (2019),Expected Years of Schooling (2020),Expected Years of Schooling (2021)
108,MCO,Monaco,Europe,Northern Hemisphere,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
132,NRU,Nauru,Oceania,Southern Hemisphere,NaN,EAP,NaN,NaN,NaN,NaN,...,10.290049,10.479331,10.672094,10.868403,11.068323,11.271921,11.479264,11.69042,11.69042,11.69042
142,PRK,North Korea,Asia,Northern Hemisphere,NaN,EAP,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,10.746180,10.777645,10.783170,10.783170,10.78317,10.78317,10.78317
158,SOM,Somalia,Africa,Northern Hemisphere,NaN,AS,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Verifiquei que os mesmos 4 países não apresentam rank de Índice de Desenvolvimento Humano, pois não estão descritos no Human Development Reports (HDR) do Programa de Desenvolvimento das Nações Unidas (UNDP). Assim, não tenho como apresentar esta informação e portanto deixarei como NaN.

### UNDP Developing Regions

In [10]:
df.loc[df['UNDP Developing Regions'].isna() ]

,ISO3,Country,Continent,Hemisphere,Human Development Groups,UNDP Developing Regions,HDI Rank (2021),Expected Years of Schooling (1990),Expected Years of Schooling (1991),Expected Years of Schooling (1992),...,Expected Years of Schooling (2012),Expected Years of Schooling (2013),Expected Years of Schooling (2014),Expected Years of Schooling (2015),Expected Years of Schooling (2016),Expected Years of Schooling (2017),Expected Years of Schooling (2018),Expected Years of Schooling (2019),Expected Years of Schooling (2020),Expected Years of Schooling (2021)
3,AND,Andorra,Europe,Northern Hemisphere,Very High,NaN,40.0,10.798780,10.798780,10.798780,...,13.524016,13.138841,13.495076,13.140280,13.300239,13.046476,13.300239,13.300239,13.300239,13.300239
8,AUS,Australia,Oceania,Southern Hemisphere,Very High,NaN,5.0,17.535079,17.505590,17.476150,...,22.625389,22.779899,22.934410,23.088921,22.747299,21.954330,20.509239,21.578011,21.054590,21.054590
9,AUT,Austria,Europe,Northern Hemisphere,Very High,NaN,25.0,13.932560,14.123510,14.421390,...,16.085060,15.848490,15.855730,15.951410,16.081190,16.092070,16.066750,16.007959,16.007959,16.007959
12,BEL,Belgium,Europe,Northern Hemisphere,Very High,NaN,13.0,14.031060,14.071650,15.307614,...,19.227631,19.415510,19.696390,19.762920,19.699909,19.774380,19.561020,19.604219,19.604219,19.604219
16,BGR,Bulgaria,Europe,Northern Hemisphere,High,NaN,68.0,12.010980,12.131460,11.967090,...,14.526010,14.908990,15.087370,14.946680,14.644910,14.414420,14.195880,13.897290,13.897290,13.897290
29,CAN,Canada,America,Northern Hemisphere,Very High,NaN,15.0,16.767969,17.126560,17.263720,...,15.659930,15.738500,15.804490,15.891400,16.009661,16.157890,16.224649,16.396259,16.396259,16.396259
30,CHE,Switzerland,Europe,Northern Hemisphere,Very High,NaN,1.0,13.426480,13.620670,13.772190,...,15.816840,15.980270,16.087140,16.194010,16.249380,16.328440,16.413271,16.500299,16.500299,16.500299
42,CYP,Cyprus,Asia,Northern Hemisphere,Very High,NaN,29.0,9.226170,9.344320,9.331640,...,13.789890,14.000920,14.256130,14.570150,14.740040,15.168870,15.356060,15.648270,15.648270,15.648270
43,CZE,Czechia,Europe,Northern Hemisphere,Very High,NaN,32.0,11.835130,11.822700,11.639230,...,16.075911,16.610161,16.748440,16.860439,16.831169,16.785110,16.238991,16.219681,16.219681,16.219681
44,DEU,Germany,Europe,Northern Hemisphere,Very High,NaN,9.0,14.560726,14.687110,14.814590,...,16.683656,16.733339,16.735340,16.789339,16.875240,16.977190,16.932091,17.010139,17.010139,17.010139
47,DNK,Denmark,Europe,Northern Hemisphere,Very High,NaN,6.0,14.061540,14.200910,14.276910,...,18.677740,19.140909,19.138531,19.237009,19.066059,18.893419,18.793699,18.714800,18.714800,18.714800
53,ESP,Spain,Europe,Northern Hemisphere,Very High,NaN,27.0,14.040100,14.295360,14.530370,...,16.956051,17.172501,17.290051,17.474470,17.540279,17.616131,17.757410,17.916901,17.916901,17.916901
54,EST,Estonia,Europe,Northern Hemisphere,Very High,NaN,31.0,13.131260,12.878290,12.837460,...,16.509911,16.423880,16.219891,16.114941,16.063620,15.921200,15.910490,15.928960,15.928960,15.928960
56,FIN,Finland,Europe,Northern Hemisphere,Very High,NaN,11.0,14.996470,15.218390,15.765560,...,17.068420,19.302570,19.261240,19.318621,19.315439,19.397120,19.476000,19.051929,19.051929,19.051929
58,FRA,France,Europe,Northern Hemisphere,Very High,NaN,28.0,14.088890,14.476250,14.697450,...,15.260720,15.412890,15.442290,15.422700,15.528430,15.645600,15.743010,15.812070,15.812070,15.812070
61,GBR,United Kingdom,Europe,Northern Hemisphere,Very High,NaN,18.0,13.654990,13.926670,14.275470,...,15.673300,17.634291,17.485910,17.328659,17.413545,17.498430,17.248051,17.309719,17.309719,17.309719
68,GRC,Greece,Europe,Northern Hemisphere,Very High,NaN,33.0,12.385340,12.936030,12.836340,...,17.164339,17.341860,17.898500,18.269515,18.640530,19.101669,19.500200,20.028790,20.028790,20.028790
72,HKG,Hong Kong,Asia,Northern Hemisphere,Very High,NaN,4.0,13.054666,13.172327,13.291049,...,15.903550,16.093330,16.319429,16.450960,16.466669,16.632450,16.929470,17.222120,17.278170,17.278170
74,HRV,Croatia,Europe,Northern Hemisphere,Very High,NaN,40.0,9.487243,9.933663,10.401089,...,14.788080,15.173510,15.273110,15.224840,15.187700,15.226720,15.181790,15.112100,15.112100,15.112100
76,HUN,Hungary,Europe,Northern Hemisphere,Very High,NaN,46.0,11.126540,11.114180,11.210510,...,15.243360,15.619690,15.425490,15.219600,15.118980,15.204180,15.129460,15.033628,15.033628,15.033628
79,IRL,Ireland,Europe,Northern Hemisphere,Very High,NaN,8.0,12.349750,12.369430,12.559160,...,17.956470,18.069645,18.182819,18.709030,18.793261,18.705290,19.756161,18.945221,18.945221,18.945221
82,ISL,Iceland,Europe,Northern Hemisphere,Very High,NaN,3.0,14.237150,15.297610,15.596360,...,18.843990,19.474751,19.589769,19.347700,19.174509,19.083090,19.175631,19.163059,19.163059,19.163059
83,ISR,Israel,Asia,Northern Hemisphere,Very High,NaN,22.0,12.873950,13.215210,13.421350,...,16.094160,16.141621,16.168930,16.171129,16.086540,16.162830,16.125259,16.050890,16.050890,16.050890
84,ITA,Italy,Europe,Northern Hemisphere,Very High,NaN,30.0,12.817480,12.992480,13.240150,...,16.466101,16.186590,16.108250,16.033369,15.978760,16.088900,16.175039,16.226789,16.226789,16.226789
87,JPN,Japan,Asia,Northern Hemisphere,Very High,NaN,19.0,13.015290,13.052800,13.065940,...,14.971597,15.036102,15.100608,15.165114,15.229620,15.215690,15.190500,15.221626,15.221626,15.221626
94,KOR,South Korea,Asia,Northern Hemisphere,Very High,NaN,19.0,13.581050,13.708010,13.716780,...,16.740049,16.650209,16.645460,16.603100,16.505470,16.481649,16.493959,16.521740,16.521740,16.521740
101,LIE,Liechtenstein,Europe,Northern Hemisphere,Very High,NaN,16.0,NaN,NaN,NaN,...,15.025540,14.830325,14.635110,14.714240,14.720930,14.883910,14.620870,15.181570,15.181570,15.181570
104,LTU,Lithuania,Europe,Northern Hemisphere,Very High,NaN,35.0,12.849780,12.639970,12.198630,...,16.673330,16.607840,16.462509,16.445080,16.499531,16.637310,16.569250,16.285061,16.285061,16.285061
105,LUX,Luxembourg,Europe,Northern Hemisphere,Very High,NaN,17.0,10.527325,10.822300,11.125541,...,13.882310,13.943130,14.003950,14.064770,14.227520,14.255820,14.315320,14.398140,14.398140,14.398140
106,LVA,Latvia,Europe,Northern Hemisphere,Very High,NaN,39.0,12.668840,12.552910,12.367560,...,15.384680,15.828710,15.817000,15.831400,15.982690,16.167690,16.230890,16.202530,16.202530,16.202530
108,MCO,Monaco,Europe,Northern Hemisphere,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
116,MLT,Malta,Europe,Northern Hemisphere,Very High,NaN,23.0,12.679610,12.824540,12.949840,...,15.165740,15.269200,15.413160,15.706120,15.847230,16.104071,16.584280,16.838570,16.838570,16.838570
129,NLD,Netherlands,Europe,Northern Hemisphere,Very High,NaN,10.0,14.674450,14.925130,14.838850,...,17.827040,17.911393,17.995746,18.080099,18.044830,18.485130,18.559931,18.693165,18.693165,18.693165
130,NOR,Norway,Europe,Northern Hemisphere,Very High,NaN,2.0,13.945500,14.246140,14.536180,...,17.474751,17.690161,17.682940,17.783890,17.969130,18.066151,18.120050,18.185200,18.185200,18.185200
133,NZL,New Zealand,Oceania,Southern Hemisphere,Very High,NaN,13.0,14.482800,14.814300,15.164740,...,18.727007,18.834860,18.803419,18.869650,18.124500,18.838570,18.878550,20.283890,20.283890,20.283890
141,POL,Poland,Europe,Northern Hemisphere,Very High,NaN,34.0,12.235260,12.272080,12.251280,...,15.340910,16.308950,15.982470,16.015189,16.047909,16.080629,16.025990,16.027149,16.027149,16.027149
143,PRT,Portugal,Europe,Northern Hemisphere,Very High,NaN,38.0,11.767670,12.222640,13.019190,...,16.303881,16.752211,16.518761,16.447281,16.374090,16.535789,16.720119,16.871229,16.871229,16.871229
147,ROU,Romania,Europe,Northern Hemisphere,Very High,NaN,53.0,11.921110,10.997550,10.566220,...,14.604780,14.614594,14.624407,14.634220,14.321490,14.259880,14.275000,14.229900,14.229900,14.229900
148,RUS,Russian Federation,Europe,Northern Hemisphere,Very High,NaN,52.0,12.824440,12.665570,12.400500,...,14.571890,14.755380,14.771520,15.129100,15.206010,15.027350,15.707240,15.766370,15.766370,15.766370
157,SMR,San Marino,Europe,Northern Hemisphere,Very High,NaN,44.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,11.892890,11.960940,12.266140,12.266140
163,SVK,Slovakia,Europe,Northern Hemisphere,Very High,NaN,45.0,11.537586,11.623158,11.709364,...,14.950830,14.932800,14.803980,14.677340,14.531800,14.487040,14.480580,14.513040,14.513040,14.513040
164,SVN,Slovenia,Europe,Northern Hemisphere,Very High,NaN,23.0,11.963990,12.049310,12.278880,...,16.989189,17.708540,17.337021,17.291990,17.500570,17.572060,17.596380,17.654921,17.654921,17.654921
165,SWE,Sweden,Europe,Northern Hemisphere,Very High,NaN,7.0,12.898350,13.001780,13.246350,...,15.792350,18.079081,18.196131,18.568600,18.832430,19.482340,19.691019,19.418530,19.418530,19.418530
184,USA,United States,America,Northern Hemisphere,Very High,NaN,21.0,15.417860,15.478030,15.739715,...,16.099891,16.148180,16.149660,16.191990,16.274481,16.310381,16.283350,16.280979,16.280979,16.280979

Analisei a coluna 'UNDP Development Region' e pude constatar que ela é aplicada à países em desenvolvimento. Assim, dos países presentes no dataset, aqueles considerados 'desenvolvidos' não estão alocados em nenhuma região.

### Expected Years of Schooling(1990 - 2021)

In [16]:
df.loc[df['Expected Years of Schooling (1990)'].isna() ]

,ISO3,Country,Continent,Hemisphere,Human Development Groups,UNDP Developing Regions,HDI Rank (2021),Expected Years of Schooling (1990),Expected Years of Schooling (1991),Expected Years of Schooling (1992),...,Expected Years of Schooling (2012),Expected Years of Schooling (2013),Expected Years of Schooling (2014),Expected Years of Schooling (2015),Expected Years of Schooling (2016),Expected Years of Schooling (2017),Expected Years of Schooling (2018),Expected Years of Schooling (2019),Expected Years of Schooling (2020),Expected Years of Schooling (2021)
7,ATG,Antigua and Barbuda,America,Northern Hemisphere,High,LAC,71.0,NaN,NaN,NaN,...,14.857500,14.759455,14.662058,14.565303,14.469187,14.373705,14.278853,14.184626,14.184626,14.184626
18,BHS,Bahamas,America,Northern Hemisphere,Very High,LAC,55.0,NaN,NaN,NaN,...,12.585772,12.644987,12.704201,12.763416,12.822630,12.822630,12.822630,12.899450,12.899450,12.899450
19,BIH,Bosnia and Herzegovina,Europe,Northern Hemisphere,High,ECA,74.0,NaN,NaN,NaN,...,14.175680,14.098067,14.020453,13.942840,13.865227,13.787613,13.787613,13.800000,13.800000,13.800000
39,CPV,Cabo Verde,Africa,Northern Hemisphere,Medium,SSA,128.0,NaN,NaN,NaN,...,13.035550,13.480580,13.400170,13.143070,13.047350,12.954100,12.704200,12.554614,12.554614,12.554614
46,DMA,Dominica,America,Northern Hemisphere,High,LAC,102.0,NaN,NaN,NaN,...,13.098067,13.129430,13.160867,13.192379,13.223968,13.255631,13.287371,13.319186,13.319186,13.319186
52,ERI,Eritrea,Africa,Northern Hemisphere,Low,SSA,176.0,NaN,NaN,NaN,...,8.377085,8.550203,8.723320,8.034710,8.042153,8.049603,8.057061,8.064525,8.064525,8.064525
59,FSM,Micronesia,Oceania,Northern Hemisphere,Medium,EAP,134.0,NaN,NaN,NaN,...,11.212077,11.176170,11.192296,11.084000,11.250260,11.419014,11.549480,11.549480,11.549480,11.549480
67,GNQ,Equatorial Guinea,Africa,Northern Hemisphere,Medium,SSA,145.0,NaN,NaN,NaN,...,8.755902,8.895764,9.035627,9.175489,9.315352,9.455215,9.595077,9.734940,9.734940,9.734940
98,LBR,Liberia,Africa,Northern Hemisphere,Low,SSA,178.0,NaN,NaN,NaN,...,9.869303,9.903696,9.977567,10.051437,10.125308,10.199178,10.273049,10.346919,10.420790,10.420790
101,LIE,Liechtenstein,Europe,Northern Hemisphere,Very High,NaN,16.0,NaN,NaN,NaN,...,15.025540,14.830325,14.635110,14.714240,14.720930,14.883910,14.620870,15.181570,15.181570,15.181570
108,MCO,Monaco,Europe,Northern Hemisphere,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
111,MDV,Maldives,Asia,Northern Hemisphere,High,SA,90.0,NaN,NaN,NaN,...,12.429241,12.458722,12.488203,12.517685,12.547166,12.576647,12.606128,12.635610,12.635610,12.635610
113,MHL,Marshall Islands,Oceania,Northern Hemisphere,Medium,EAP,131.0,NaN,NaN,NaN,...,11.033165,10.919759,10.806352,10.692946,10.579539,10.466133,10.352726,10.239320,10.239320,10.239320
118,MNE,Montenegro,Europe,Northern Hemisphere,Very High,ECA,49.0,NaN,NaN,NaN,...,15.013893,14.984730,14.955566,14.926403,14.897240,15.021320,14.999680,14.945200,15.081610,15.081610
132,NRU,Nauru,Oceania,Southern Hemisphere,NaN,EAP,NaN,NaN,NaN,NaN,...,10.290049,10.479331,10.672094,10.868403,11.068323,11.271921,11.479264,11.690420,11.690420,11.690420
139,PLW,Palau,Oceania,Northern Hemisphere,High,EAP,80.0,NaN,NaN,NaN,...,16.397155,16.590111,16.474998,16.359885,16.244772,16.129659,16.014546,15.899433,15.784320,15.784320
142,PRK,North Korea,Asia,Northern Hemisphere,NaN,EAP,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,10.746180,10.777645,10.783170,10.783170,10.783170,10.783170,10.783170
145,PSE,"Palestine, State of",Asia,Northern Hemisphere,High,AS,106.0,NaN,NaN,NaN,...,13.308610,13.105190,13.172030,13.209280,13.195610,13.364070,13.409400,13.405590,13.358010,13.358010
157,SMR,San Marino,Europe,Northern Hemisphere,Very High,NaN,44.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,11.892890,11.960940,12.266140,12.266140
158,SOM,Somalia,Africa,Northern Hemisphere,NaN,AS,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
160,SSD,South Sudan,Africa,Northern Hemisphere,Low,SSA,191.0,NaN,NaN,NaN,...,5.139976,5.274154,5.408332,5.542510,5.542510,5.542510,5.542510,5.542510,5.542510,5.542510
173,TKM,Turkmenistan,Asia,Northern Hemisphere,High,ECA,91.0,NaN,NaN,NaN,...,11.440636,11.751581,12.062526,12.373471,12.684417,12.767204,12.849992,12.932780,13.210400,13.210400
174,TLS,Timor-Leste,Asia,Southern Hemisphere,Medium,EAP,140.0,NaN,NaN,NaN,...,12.937900,12.653090,12.517450,12.490890,12.398220,12.398220,12.398220,12.616098,12.616098,12.616098
189,VUT,Vanuatu,Oceania,Southern Hemisphere,Medium,EAP,140.0,NaN,NaN,NaN,...,11.096887,11.158628,11.220369,11.282110,11.344885,11.408010,11.471486,11.535315,11.535315,11.535315

Verifiquei os dados faltantes referentes aos anos de 1990 até 2021. A ausencia de informação pode servir de comparação com outros países, portanto manterei os dados no datase.